apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-deployment
spec:
  selector:
    matchLabels:
      app: testapp
  replicas: 8 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: testapp
        #image: patrickkutch/testapp:stress
        image: patrickkutch/testapp:v1
        imagePullPolicy: Always
        env:
        - name: PYTHONUNBUFFERED
          value: "0"        
        resources:
          limits:
            cpu: "1"
          requests:
           cpu: "0.5"
        ports:
        - name: app-port 
          containerPort: 80
        
